--- #YAML:1.0
name:                Catalyst-Plugin-Authentication-Credential-HTTP
version:             0.08
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Catalyst:                      5.49
    Catalyst::Plugin::Authentication: 0
    Data::UUID:                    0.11
    String::Escape:                0
    Test::Exception:               0
    Test::MockObject:              1.01
    URI::Escape:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
