---
abstract: 'HTTP Basic and Digest authentication'
author:
  - 'Yuval Kogman, C<nothingmuch@woobling.org>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-Authentication-Credential-HTTP
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Plugin::Authentication: 0
  Catalyst::Runtime: 0
  Data::UUID: 0.11
  String::Escape: 0
  Test::Exception: 0
  Test::MockObject: 0
  URI::Escape: 0
version: 0.11
